### ISSUE TITLE
Multiple/Duplicate icons for some applications

### ISSUE THREAD

**Issue by colonelpanic8** [IvanMalison/gtk-sni-tray#10]
I think that this likely occurs because some applications attempt to support both AppIndicator and SNI tray. This leads to issues in gtk-sni-tray because we actually handle both.

**Comment by colonelpanic8** [comment]
In many cases one of the icons will remain even though it does nothing, not sure why this is.

**Comment by ARR8** [comment]
For me this ties into #12, as only one of these icons will have the correct color.

**Comment by colonelpanic8** [comment]
@ARR8 Yes, that is unsurprising. These icons are actually using a different protocol (passing icon names instead of passing raw pixel data)

**Comment by colonelpanic8** [comment]
@ARR8 Is there an environment that you have working where things work "as you expect"?

What environment is that?

**Comment by ARR8** [comment]
Yes - I've been using the JWM tray.

**Comment by colonelpanic8** [comment]
@ARR8 Is that an SNI/Appindicator or xembed tray?

**Comment by ARR8** [comment]
I'm not sure. It seems to support both options in onboard mentioned in #11.

If it helps, another program that worked, though one I do not use anymore, was lxqt-panel, which uses StatusNotifier with an xembed fallback.

**Comment by colonelpanic8** [comment]
@ARR8 I figured out the issue here. It seems that many of these qt SNIs send out the signals that icons are updated over dbus connections that are NOT the same as the ones they actually register/host their icons on.

IMO, this is out of spec, and the issue should really be fixed in the indicators, BUT

I have pushed a fix to https://github.com/IvanMalison/status-notifier-item

There's a temporary branch
https://github.com/taffybar/gtk-sni-tray/tree/SNIQTFixes

Where you can check those fixes out on the standalone tray

@ARR8 Can you verify that the duplicate icon issue goes away with this change?

**Comment by ARR8** [comment]
No, same issue. I've double-checked that I'm compiling correctly from the new branch.

**Comment by colonelpanic8** [comment]
@ARR8 Can you run with

-l DEBUG

ignore the stuff that happens on startup (press enter a bunch to separate the output) and then start the application that causes duplicates?

@ARR8 And you made sure to stack install rather than stack build, right?

**Comment by colonelpanic8** [comment]
@ARR8 Do you at least see the color fix? If the colors are not different, you definitely aren't using the new code.

**Comment by ARR8** [comment]
Oh, I think I see the problem. I used a modified PKGBUILD rather than stack. Looking at the commits, none of the code actually changed except for build instructions, which are ignored.

Rather than installing stack and getting a whole Haskell build environment on this machine, I'll just recompile the changed dependencies. Which ones are those?

**Comment by colonelpanic8** [comment]
status-notifier-item changed, but i havent made a release yet, because I want to make sure that everything is fixed.

**Comment by colonelpanic8** [comment]
you'll need to install status-notifier-item from its master

**Comment by ARR8** [comment]
Fixed for me.

**Comment by illis** [comment]
Just tried building with
```
- git: http://github.com/taffybar/gtk-sni-tray.git
  commit: ea72ad0571def77ac20e8b11d1d966a5735f91d9
  #- gtk-sni-tray-0.1.3.1
- git: https://github.com/IvanMalison/status-notifier-item
  commit: e0d1d7867e8fe593745659e3604ecdf191a2ab3f
  #- status-notifier-item-0.2.2.0
```
Inside the taffybar stack.yaml and still got the double icon with vlc. Colours weren't changed either - which I'm guessing means, that I missed something somewhere?

**Comment by illis** [comment]
Actually ignore that last remark. It's working for me :) - was building out of the wrong directory - rookie mistake, yes I know!

**Comment by colonelpanic8** [comment]
@illis great!
