### ISSUE TITLE
Incorrect colors in icons

### ISSUE THREAD

**Issue by ARR8** [IvanMalison/gtk-sni-tray#12]
It seems that red/orange are swapped with blue. For example, QtPass, which should have a blue icon, appears orange. VLC, Kleopatra, and lxqt-powermanagement when the power is low, should be orange/red/red, but all appear blue. Other colors, such as lxqt-powermanagement when the power is high (green) are fine.

**Comment by colonelpanic8** [comment]
This is fixed in https://github.com/IvanMalison/status-notifier-item/commit/e0d1d7867e8fe593745659e3604ecdf191a2ab3f

Which is available in (for now in https://github.com/taffybar/gtk-sni-tray/tree/SNIQTFixes)

**Comment by ARR8** [comment]
Confirmed fixed.

**Comment by colonelpanic8** [comment]
Let's leave this open until the fix actually makes it in to a release
