### ISSUE TITLE
Support Activate and SecondaryActivate

### ISSUE THREAD

**Issue by ARR8** [IvanMalison/gtk-sni-tray#14]
Clicking on icons seems to always show the right-click menu, and there is no way to trigger the left-click action. For some programs, this means an extra click to "show" or "open," but some programs do not have the left-click functionality in the right-click menu.

**Comment by colonelpanic8** [comment]
Yes, the Host implementation is, as you have noticed, not technically complete, although the reality is that very few things properly implement the activate or secondaryACtivate methods here

https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/StatusNotifierItem/

This is generally one of the downsides of SNI as compared to XEMBED. There is a bit less flexibility WRT input.

**Comment by colonelpanic8** [comment]
@ARR8 @kurnevsky @nomeata You all expressed interest in this feature -- Do you have examples of sni apps that provide this functionality? @kurnevsky has implemented this in the latest version, but I haven't found any examples that I can use for testing.

**Comment by kurnevsky** [comment]
@IvanMalison
For activate: qbittorrent, qtox, telegram-desktop, deadbeef use it for window showing/hiding.
For secondary activate:
deadbeef with https://github.com/vovochka404/deadbeef-statusnotifier-plugin uses it for play/pause toggle. Derivation: https://github.com/NixOS/nixpkgs/pull/130534
pidgin with https://github.com/philipl/pidgin-indicator uses it to show/hide its roster. Derivation: https://github.com/kurnevsky/nixfiles/blob/master/modules/pidgin-indicator.nix

**Comment by colonelpanic8** [comment]
@kurnevsky I'm going to do a release of gtk-sni-tray soon (probably today). I've merged https://github.com/taffybar/status-notifier-item/pull/8 . Were there some associated changes you wanted to make here that needed that PR?

**Comment by kurnevsky** [comment]
> Were there some associated changes you wanted to make here that needed that PR?

Yes. I haven't tested it yet, but should be enough (itemIsMenu is available there and it defines the behavior of left button).

**Comment by colonelpanic8** [comment]
Does it? I don't see the code that does that.

**Comment by kurnevsky** [comment]
I mean specs say it defines :)
We should implement it in `gtk-sni-tray` with the help of `itemIsMenu`.
