### ISSUE TITLE
Possibly incomplete WM hints

### ISSUE THREAD

**Issue by ARR8** [IvanMalison/gtk-sni-tray#15]
Although the program correctly docks to the top of the screen and prevents maximized programs from overlapping it, it also shows up in the task list as a normal window and is minimizable from there.

**Comment by colonelpanic8** [comment]
Hmm, not sure what to make of this. The code is actually shared between gtk-sni-tray and taffybar in gtk-strut. Everything should be exactly the same.

**Comment by ARR8** [comment]
To be clear, I have not tested taffybar under a stacking WM yet. It may have the same problem.

**Comment by ARR8** [comment]
I've confirmed that taffybar has the same problem. Should I file an issue there?

**Comment by colonelpanic8** [comment]
sure

**Comment by colonelpanic8** [comment]
or maybe file it on gtk-strut

**Comment by colonelpanic8** [comment]
https://github.com/IvanMalison/gtk-strut

**Comment by colonelpanic8** [comment]
Closed in favor of gtk-strut issue
