### ISSUE TITLE
Can this be made swallowable inside another dock?

### ISSUE THREAD

**Issue by frankspace** [IvanMalison/gtk-sni-tray#23]
Hello!  I'm trying to find a substitute for stalonetray that can deal with this newfangled SNI stuff, for use with FVWM.  Presently, stalonetray can be "swallowed" by telling it to use a specific geometry (rather than a percentage of the screen) and not try to do anything like handle its own placement on the screen or anything like that.  Is there a way to do something similar with gtk-sni-tray?  Thank you!

**Comment by colonelpanic8** [comment]
@frankspace this is not possible at present. But it should be quite easy to make it work. I'll have to look at exactly what stalonetray is doing when no_shrink is set to true, but if its as simple as not making struts and not doing anything at a ll with geometry it should be quite easy to make it work.

**Comment by colonelpanic8** [comment]
@frankspace are you able to build gtk-sni-tray from source? I'm not entirely sure how to test that we are achieving the behavior that you want

**Comment by frankspace** [comment]
@IvanMalison That'd be awesome, although I certainly appreciate that you're busy.

Also, alas, no, I cannot build this from source; I spent a very long time trying on Arch, including needing to create a number of haskell packages that didn't exist and updating one or two that were out of date, until I finally ran into one that didn't compile and nobody seemed to know why.  I don't know anything about haskell, personally.  I gave up and created a PKGBUILD that pulls binaries (and a dependency) from Debian.  I'd be happy to paste that PKGBUILD here, if it'd serve as any kind of useful reference.

**Comment by frankspace** [comment]
Oh.  Derp.  So I realized the point of your question just after clicking comment.  Yeah, I guess there really is no way I'd be able to test that.

**Comment by colonelpanic8** [comment]
@frankspace can you install nix package manager. The nix build for this is literally a one command build. Should do everything.

**Comment by colonelpanic8** [comment]
https://nixos.org/nix/

**Comment by colonelpanic8** [comment]
https://wiki.archlinux.org/index.php/Nix

**Comment by colonelpanic8** [comment]
@frankspace if you can build from source, the no-strut option should do what you what you want.
