### ISSUE TITLE
SNITray.hs does not exist

### ISSUE THREAD

**Issue by kpbochenek** [IvanMalison/gtk-sni-tray#3]
in `README` there is a link pointing to `SNITray.hs` in taffybar, no such file exists in that project.

**Comment by colonelpanic8** [comment]
@kpbochenek It just moved https://github.com/taffybar/taffybar/blob/master/src/System/Taffybar/Widget/SNITray.hs

I'll fix the link

**Comment by kpbochenek** [comment]
Link works :+1:
